version: '2'

services:
  mysql:
    image: mysql:5.7.21
    container_name: mysql-sonar
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "sonar"
      MYSQL_USER: "sonar"
      MYSQL_PASSWORD: "sonar"
    ports:
      - 3306:3306
    volumes:
      - ~/mysql-data:/var/lib/mysql
    restart: always

  sonar:
    depends_on:
      - mysql
    image: sonar-scala
    container_name: sonar-scala
    environment:
      SONARQUBE_JDBC_USERNAME: "sonar"
      SONARQUBE_JDBC_PASSWORD: "sonar"
      SONARQUBE_JDBC_URL: "jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"
    ports:
      - 9000:9000
    links:
      - mysql:mysql
    restart: always
